# Generated by Django 5.2 on 2025-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[(2, 'finished'), (1, 'in_progress'), (0, 'init')], default='init'),
        ),
    ]
