# Generated by Django 5.2 on 2025-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='init', max_length=20),
        ),
    ]
