# Generated by Django 5.2 on 2025-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'finished'), (0, 'init'), (1, 'in_progress')], default=0),
        ),
    ]
