# Generated by Django 5.2 on 2025-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'init'), (1, 'in_progress'), (2, 'finished')], default=0),
        ),
    ]
