# Generated by Django 5.2 on 2025-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_position_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
