# Generated by Django 5.2 on 2025-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_collectibleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
