# Generated by Django 5.2 on 2025-07-22 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_collectibleitem_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
