# Generated by Django 5.2 on 2025-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='run_time_seconds',
        ),
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
