# Generated by Django 5.2 on 2025-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_remove_run_run_time_seconds_position_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
