# Generated by Django 5.2 on 2025-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(choices=[('Сделай 10 Забегов!', 'Сделай 10 Забегов!'), ('Пробеги 50 километров!', 'Пробеги 50 километров!'), ('2 километра за 10 минут!', '2 километра за 10 минут!')], max_length=255),
        ),
    ]
