# Generated by Django 5.2 on 2025-08-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0018_alter_challenge_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, null=True),
        ),
    ]
